services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
  db:
    image: mysql:8
    restart: always
    ports:
      - '3306:3306'
    expose: 
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin